Rund=round(1000*BestPAa(4,:,2))/1000;
Para='';
for i=1:length(AtoZ)
    Para= [Para,...
    NumbersText{floor(Rund(i)+1)}, ' point ',...
    NumbersText{ floor(10*(Rund(i)-floor(Rund(i))))+1},' ',...
    NumbersText{floor(10*(10*Rund(i)-floor(10*Rund(i))))+1},' ',...
    NumbersText{round(10*(100*Rund(i)-floor(100*Rund(i))))+1},' percent are ',char(64+i),'’s, '];
end